/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.banhang.view.viewlogin.login;

/**
 *
 * @author vinhnv
 */
public class Register extends PalnelCustom {
    
    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField1 = new com.mycompany.banhang.view.viewlogin.swing.TextField();
        textField2 = new com.mycompany.banhang.view.viewlogin.swing.TextField();
        textField3 = new com.mycompany.banhang.view.viewlogin.swing.TextField();
        textField4 = new com.mycompany.banhang.view.viewlogin.swing.TextField();
        textField5 = new com.mycompany.banhang.view.viewlogin.swing.TextField();
        textField6 = new com.mycompany.banhang.view.viewlogin.swing.TextField();
        jLabel1 = new javax.swing.JLabel();
        txt_soDienThoai = new com.mycompany.banhang.view.viewlogin.swing.TextField();
        txt_fillName = new com.mycompany.banhang.view.viewlogin.swing.TextField();
        txt_emailSignUp = new com.mycompany.banhang.view.viewlogin.swing.TextField();
        txt_passwordSignUp = new com.mycompany.banhang.view.viewlogin.swing.Password();
        btn_SignUp = new com.mycompany.banhang.view.viewlogin.swing.Button();

        setBackground(new java.awt.Color(56, 56, 56));

        jLabel1.setBackground(new java.awt.Color(242, 242, 242));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SIGN UP");

        txt_soDienThoai.setForeground(new java.awt.Color(242, 242, 242));
        txt_soDienThoai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_soDienThoai.setHint("Số điện thoại");

        txt_fillName.setForeground(new java.awt.Color(242, 242, 242));
        txt_fillName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_fillName.setHint("FULL NAME");

        txt_emailSignUp.setForeground(new java.awt.Color(242, 242, 242));
        txt_emailSignUp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_emailSignUp.setHint("EMAIL");

        txt_passwordSignUp.setForeground(new java.awt.Color(242, 242, 242));
        txt_passwordSignUp.setHint("PASSWORD");

        btn_SignUp.setBackground(new java.awt.Color(86, 142, 255));
        btn_SignUp.setForeground(new java.awt.Color(255, 255, 255));
        btn_SignUp.setText("Sign Up");
        btn_SignUp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_emailSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(txt_fillName, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(txt_soDienThoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_passwordSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_SignUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(8, 8, 8)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(txt_fillName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(txt_emailSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(txt_soDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(txt_passwordSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btn_SignUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.banhang.view.viewlogin.swing.Button btn_SignUp;
    private javax.swing.JLabel jLabel1;
    private com.mycompany.banhang.view.viewlogin.swing.TextField textField1;
    private com.mycompany.banhang.view.viewlogin.swing.TextField textField2;
    private com.mycompany.banhang.view.viewlogin.swing.TextField textField3;
    private com.mycompany.banhang.view.viewlogin.swing.TextField textField4;
    private com.mycompany.banhang.view.viewlogin.swing.TextField textField5;
    private com.mycompany.banhang.view.viewlogin.swing.TextField textField6;
    private com.mycompany.banhang.view.viewlogin.swing.TextField txt_emailSignUp;
    private com.mycompany.banhang.view.viewlogin.swing.TextField txt_fillName;
    private com.mycompany.banhang.view.viewlogin.swing.Password txt_passwordSignUp;
    private com.mycompany.banhang.view.viewlogin.swing.TextField txt_soDienThoai;
    // End of variables declaration//GEN-END:variables
}
